language: python
cache: pip
python:
    - "3.7"
before-install:
    - pip install -r requirements.txt
install:
    - python setup.py install
script:
    - cd test
    - pytest test.py --cov=pipescaler --cov-report=term-missing
after-success:
    - coveralls
