language: python
os: linux
cache: pip
python: 3.8
before-install:
  - export PYTHONPATH="${TRAVIS_BUILD_DIR}:${PATH}"
script:
  - cd ${TRAVIS_BUILD_DIR}/test
  - pytest -v --cov=pipescaler --cov-report term
