language: python
os:
  - linux
cache: pip
python:
    - "3.8"
before-install:
    - pip install -r requirements.txt
    - sudo apt-get update
    - sudo apt -y install imagemagick libsdl2-dev libsdl2-image-dev pngquant potrace
    - bash -ex ${TRAVIS_BUILD_DIR}/test/scripts/download_models.sh
    - bash -ex ${TRAVIS_BUILD_DIR}/test/scripts/install_xbrzscale.sh
    - export PATH="${TRAVIS_BUILD_DIR}/xbrzscale:${PATH}"
    - export PYTHONPATH="${TRAVIS_BUILD_DIR}:${PATH}"
#install:
#    - python setup.py install
script:
    - cd test
    - pytest test.py --cov=pipescaler --cov-report=term
after-success:
    - coveralls
