language: python
os:
  - linux
cache: pip
python:
    - "3.7"
before-install:
    - pip install -r requirements.txt
    - sudo apt-get update
    - sudo apt -y install potrace
install:
    - python setup.py install
script:
    - cd test
    - pytest test.py --cov=pipescaler --cov-report=term
after-success:
    - coveralls
