language: python
os:
  - linux
cache: pip
python:
  - "3.8"
before-install:
#   - bash -ex ${TRAVIS_BUILD_DIR}/test/scripts/download_models.sh
  - export PYTHONPATH="${TRAVIS_BUILD_DIR}:${PATH}"
  - echo $PYTHONPATH
script:
  - cd ${TRAVIS_BUILD_DIR}/test
  - pytest --cov=../pipescaler --cov-report term ./test_processors.py
