name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PipeScaler
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update
        sudo apt -y install pngquant
        sudo apt -y install potrace
    - name: Prospector
      run: |
        cd ${GITHUB_WORKSPACE}/pipescaler
        prospector .
    - name: Install
      run: |
        cd ${GITHUB_WORKSPACE}
        python setup.py build
        python setup.py install
    - name: Test with pytest
      run: |
        export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
        cd ${GITHUB_WORKSPACE}/test
        pytest -v --cov=pipescaler --cov-report term .
