name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Determine default branch
        run: echo "DEFAULT_BRANCH=${GITHUB_BASE_REF:-${{ github.event.repository.default_branch }}}" >> $GITHUB_ENV

      - name: Fetch default branch
        run: git fetch origin $DEFAULT_BRANCH

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pngquant potrace

      - name: Install package dependencies
        run: uv sync --all-extras --dev

      - name: Install package
        run: uv pip install -e .

      - name: Run ruff
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/outputs
          cd ${GITHUB_WORKSPACE}
          uv run ruff check | tee ${GITHUB_WORKSPACE}/.github/outputs/ruff.txt || echo

      - name: Annotate with ruff results
        uses: KarlTDebiec/LinterPrinter@main
        with:
          tool: ruff
          tool_infile: .github/outputs/ruff.txt

      - name: Run pyright
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/outputs
          cd ${GITHUB_WORKSPACE}
          uv run pyright . | tee ${GITHUB_WORKSPACE}/.github/outputs/pyright.txt || echo

      - name: Annotate with pyright results
        uses: KarlTDebiec/LinterPrinter@main
        with:
          tool: pyright
          tool_infile: .github/outputs/pyright.txt

      - name: Run pytest
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/outputs
          export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
          cd ${GITHUB_WORKSPACE}/test
          uv run pytest -v --cov=pipescaler --cov-report term . | tee ${GITHUB_WORKSPACE}/.github/outputs/pytest.txt || echo
        continue-on-error: true

      - name: Annotate with pytest results
        uses: KarlTDebiec/LinterPrinter@main
        with:
          tool: pytest
          tool_infile: .github/outputs/pytest.txt

  macOS:
    runs-on: macos-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install system dependencies
        run: |
          brew install cairo pngquant potrace

      - name: Set up uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install package dependencies
        run: uv sync --all-extras --dev

      - name: Install package
        run: uv pip install -e .

      - name: Run tests
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/outputs
          export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
          cd ${GITHUB_WORKSPACE}/test
          uv run pytest -v --cov=pipescaler --cov-report term . | tee ${GITHUB_WORKSPACE}/.github/outputs/pytest.txt || echo

      - name: Annotate with pytest results
        uses: KarlTDebiec/LinterPrinter@main
        with:
          tool: pytest
          tool_infile: .github/outputs/pytest.txt

  Windows:
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Set up uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install system dependencies
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path .\executables | Out-Null
          iwr -Uri http://potrace.sourceforge.net/download/1.16/potrace-1.16.win64.zip -OutFile potrace.zip
          Expand-Archive -Path potrace.zip -DestinationPath .\executables
          Move-Item -Path .\executables\potrace-1.16.win64\* -Destination .\executables -Force
          Remove-Item -Recurse -Force .\executables\potrace-1.16.win64
          iwr -Uri https://github.com/microsoft/DirectXTex/releases/download/nov2021/texconv.exe -OutFile .\executables\texconv.exe
          echo "$(Get-Location)\executables" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install package
        run: uv pip install -e .

      - name: Run tests
        shell: bash
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/outputs
          export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
          cd ${GITHUB_WORKSPACE}/test
          uv run pytest -v --cov=pipescaler --cov-report term . | tee ${GITHUB_WORKSPACE}/.github/outputs/pytest.txt || echo

      - name: Annotate with pytest results
        uses: KarlTDebiec/LinterPrinter@main
        with:
          tool: pytest
          tool_infile: .github/outputs/pytest.txt
