name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
#     build-linux:
#         runs-on: ubuntu-latest
#         steps:
#         - name: Checkout PipeScaler
#           uses: actions/checkout@v2
#           with:
#               submodules: true
#         - name: Set up Python 3.8
#           uses: actions/setup-python@v2
#           with:
#               python-version: "3.8"
#         - name: Install dependencies
#           run: |
#               python -m pip install --upgrade pip
#               pip install -r requirements.txt
#               sudo apt update
#               sudo apt -y install pngquant
#               sudo apt -y install potrace
#         - name: prospector
#           run: |
#               cd ${GITHUB_WORKSPACE}
#               prospector -0 pipescaler
#         - name: pydocstyle
#           run: |
#               cd ${GITHUB_WORKSPACE}
#               pydocstyle pipescaler || echo
#         - name: Install
#           run: |
#               cd ${GITHUB_WORKSPACE}
#               python setup.py build
#               python setup.py install
#         - name: Test with pytest
#           run: |
#               export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
#               cd ${GITHUB_WORKSPACE}/test
#               pytest -v --cov=pipescaler --cov-report term .
#
#     build-macos:
#         runs-on: macos-latest
#         steps:
#         - name: Checkout PipeScaler
#           uses: actions/checkout@v2
#           with:
#               submodules: true
#         - name: Set up Python 3.8
#           uses: actions/setup-python@v2
#           with:
#               python-version: "3.8"
#         - name: Install dependencies
#           run: |
#               python -m pip install --upgrade pip
#               pip install -r requirements.txt
#               brew install pngquant
#               brew install potrace
#         - name: Install
#           run: |
#               cd ${GITHUB_WORKSPACE}
#               python setup.py build
#               python setup.py install
#         - name: Test with pytest
#           run: |
#               export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
#               cd ${GITHUB_WORKSPACE}/test
#               pytest -v --cov=pipescaler --cov-report term .

    build-windows:
        runs-on: windows-latest
        steps:
        - name: Checkout PipeScaler
          uses: actions/checkout@v2
          with:
              submodules: true
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: "3.8"
        - name: Install dependencies
          run: |
              Set-PSDebug -Trace 1
              $ErrorView = 'NormalView'
              Set-Location -Path ${env:GITHUB_WORKSPACE}
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pywinauto
              choco install pngquant
              Invoke-WebRequest -Uri http://potrace.sourceforge.net/download/1.16/potrace-1.16.win64.zip -Outfile potrace-1.16.win64.zip
              Expand-Archive potrace-1.16.win64.zip
              echo "${env:GITHUB_WORKSPACE}\potrace-1.16.win64\potrace-1.16.win64" | Out-File -FilePath $env:GITHUB_PATH
              Invoke-WebRequest -Uri https://github.com/microsoft/DirectXTex/releases/download/nov2021/texconv.exe -Outfile texconv.exe
              echo "${env:GITHUB_WORKSPACE}" | Out-File -FilePath $env:GITHUB_PATH
        - name: Install
          run: |
              $ErrorView = 'NormalView'
              Set-Location -Path ${env:GITHUB_WORKSPACE}
              python setup.py build
              python setup.py install
        - name: Test with pytest
          run: |
              $ErrorView = 'NormalView'
              ${env:PACKAGE_ROOT}="${env:GITHUB_WORKSPACE}\pipescaler"
              Set-Location ${env:GITHUB_WORKSPACE}\test
              pytest -v processors\external\test_potrace.py
              pytest -v processors\external\test_texconv.py
