name: macOS

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-macos:
        runs-on: macos-latest
        if: github.event.pull_request.draft == false
        steps:
        - name: Checkout PipeScaler
          uses: actions/checkout@v2
          with:
              submodules: true
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: "3.8"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              brew install pngquant
              brew install potrace
        - name: Install
          run: |
              cd ${GITHUB_WORKSPACE}
              python setup.py build
              python setup.py install
        - name: Test with pytest
          run: |
              export PACKAGE_ROOT=${GITHUB_WORKSPACE}/pipescaler
              cd ${GITHUB_WORKSPACE}/test
              pytest -v --cov=pipescaler --cov-report term .
