name: Linux2

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout PipeScaler
          uses: actions/checkout@v2
          with:
              submodules: true
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
